{{- if .Values.externalSecret.enabled }}
{{- if eq .Values.externalSecret.provider "gcp" }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-sm
  namespace: {{ .Values.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecret.gcp.projectID | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecret.gcp.clusterLocation | quote }}
          clusterName: {{ .Values.externalSecret.gcp.clusterName | quote }}
          serviceAccountRef:
            name: {{ include "bugsink.serviceAccountName" . }}
{{- else if eq .Values.externalSecret.provider "aws" }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-sm
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "bugsink.serviceAccountName" . }}
{{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Release.Name }}-sm
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Merge
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: {{ if eq .Values.externalSecret.provider "gcp" }}{{ .Values.externalSecret.gcp.secretKeyRemote }}{{ else }}{{ .Values.externalSecret.aws.secretKeyRemote }}{{ end }}
  - secretKey: DB_PASSWORD
    remoteRef:
      key: {{ if eq .Values.externalSecret.provider "gcp" }}{{ .Values.externalSecret.gcp.dbPasswordRemote }}{{ else }}{{ .Values.externalSecret.aws.dbPasswordRemote }}{{ end }}
{{- end }}
